# Generated by Django 5.2.17 on 2026-08-24 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(help_text="Identifiant unique pour l'URL (ex: chicken-tenders)", unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'extra")),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (FCFA)')),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
            },
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la sauce')),
                ('additional_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prix supplémentaire (FCFA)')),
            ],
            options={
                'verbose_name': 'Sauce',
                'verbose_name_plural': 'Sauces',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description du plat')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix de base (FCFA)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Photo du plat')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible à la vente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category', verbose_name='Catégorie')),
                ('extras', models.ManyToManyField(blank=True, to='menu.extra', verbose_name='Extras associables')),
                ('sauces', models.ManyToManyField(blank=True, to='menu.sauce', verbose_name='Sauces associables')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
