# Generated by Django 5.2.17 on 2026-08-24 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Téléphone WhatsApp')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (Optionnel)')),
                ('order_type', models.CharField(choices=[('delivery', 'Livraison à domicile'), ('takeaway', 'À emporter')], default='delivery', max_length=20, verbose_name='Type de commande')),
                ('delivery_zone', models.CharField(blank=True, max_length=100, verbose_name='Zone de livraison (ex: Mermoz, Plateau)')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Adresse / Repère de livraison')),
                ('notes', models.TextField(blank=True, verbose_name='Instructions particulières')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Montant total (FCFA)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix unitaire appliqué (FCFA)')),
                ('extras', models.ManyToManyField(blank=True, to='menu.extra', verbose_name='Extras choisis')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.product', verbose_name='Produit')),
                ('sauce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.sauce', verbose_name='Sauce choisie')),
            ],
            options={
                'verbose_name': 'Article commandé',
                'verbose_name_plural': 'Articles commandés',
            },
        ),
    ]
